version: 2
updates:
  # App dependencies (pnpm uses the npm ecosystem; it reads pnpm-lock.yaml)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    rebase-strategy: auto
    labels: ["dependencies"]
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Group minor & patch bumps into one PR (less noise)
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    # Avoid surprise majors on core frameworks/types
    ignore:
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react-dom"
        update-types: ["version-update:semver-major"]

  # GitHub Actions (your CI)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:15"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels: ["dependencies", "ci"]
