name: "Bug report"
description: "Report a problem with the starter"
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Steps to reproduce + expected vs actual
    validations: { required: true }