[[hooks]]
event = "PostToolUse"
command = "./scripts/claude-hook-dispatcher.sh $CLAUDE_FILE_PATHS"
run_in_background = true

[hooks.matcher]
tool_name = "edit_file"
file_paths = ["src/app/**/*","src/components/**/*","src/lib/**/*","src/styles/**/*","tests/**/*","__tests__/**/*"]