name: setup-pnpm
on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
          run_install: false

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'pnpm'

      - name: Print versions
        run: node -v && pnpm -v

      - name: Ensure pnpm present (guard)
        run: |
          if ! command -v pnpm >/dev/null 2>&1; then
            corepack enable
            corepack prepare "$(node -p "require('./package.json').packageManager")" --activate
          fi
          pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Ensure lockfile unchanged
        run: |
          if ! git diff --quiet -- pnpm-lock.yaml; then
            echo "::error title=Lockfile changed during install::Commit pnpm-lock.yaml before pushing."
            git --no-pager diff -- pnpm-lock.yaml | sed -n '1,200p'
            exit 1
          fi