name: Automerge Dependabot (minor/patch)
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch metadata
        id: meta
        uses: dependabot/fetch-metadata@v2
      - name: Enable auto-merge for minor/patch
        if: contains('minor,patch', steps.meta.outputs.update-type)
        uses: peter-evans/enable-pull-request-automerge@v4
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash