name: PR Autofill

on:
  pull_request_target:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  ensure-body:
    # Optional guard so it never runs on pushes
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base (trusted) ref
        uses: actions/checkout@v4
        with:
          # Under pull_request_target, always read files from the base repo/commit
          ref: ${{ github.event.pull_request.base.sha }}
          fetch-depth: 1

      - name: Load template
        id: tpl
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const fs = require('fs');
            return fs.readFileSync('.github/pull_request_template.md', 'utf8');

      - name: Patch PR body if missing/placeholder
        uses: actions/github-script@v7
        with:
          script: |
            // Current PR body
            const pr = context.payload.pull_request;
            const body = (pr?.body || "");

            // Consider "empty" and common placeholder cases
            const looksEmpty = body.trim().length < 50;
            const cleaned = body.replace(/<!--[\s\S]*?-->/g, ''); // ignore HTML comments
            const isPlaceholder = /(##\s*Summary\b)|Summary:\s*_?What changed/i.test(cleaned);

            // Template loaded in env
            const tpl = process.env.TEMPLATE;
            if (!tpl || tpl.trim().length < 10) {
              core.setFailed("Template is empty or missing.");
              return;
            }

            if (looksEmpty || isPlaceholder) {
              await github.rest.pulls.update({
                ...context.repo,
                pull_number: pr.number,
                body: tpl
              });
              core.notice("PR body was empty/placeholder → filled from template.");
            } else {
              core.info("PR body looks good. No change.");
            }
        env:
          TEMPLATE: ${{ steps.tpl.outputs.result }}
