name: PR Autofill
on:
  pull_request_target:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  ensure-body:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Load template
        id: load_template
        shell: bash
        run: |
          {
            echo 'TEMPLATE<<EOF'
            cat .github/pull_request_template.md
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Preview template first 5 lines
        run: |
          echo "${{ steps.load_template.outputs.TEMPLATE }}" | head -n 5

      - name: Patch PR body if missing/placeholder
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || "";
            const looksEmpty = body.trim().length < 50;
            const isPlaceholder = /Summary\s*_What changed/.test(body);
            
            if (looksEmpty || isPlaceholder) {
              await github.rest.pulls.update({
                ...context.repo,
                pull_number: context.payload.number,
                body: process.env.TEMPLATE
              });
              core.notice("PR body was empty/placeholder → filled from template.");
            } else {
              core.info("PR body looks good. No change.");
            }
        env:
          TEMPLATE: ${{ steps.load_template.outputs.TEMPLATE }}