name: release
on:
  push:
    branches: ["main"]
permissions:
  contents: write
  pull-requests: write
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with: 
          node-version: 20
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with: 
          version: 9
          run_install: false
      - run: pnpm install --frozen-lockfile
      - run: pnpm changeset version
      - run: git config user.name "github-actions[bot]" && git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git add -A && git commit -m "chore(release): version packages" || echo "No changes to release"
      - run: git push
  tag:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --tags
      - run: |
          if [ -f ".changeset/config.json" ]; then
            VERSION=$(node -p "require('./package.json').version")
            if ! git tag | grep -q "v$VERSION"; then
              git tag "v$VERSION"
              git push --follow-tags
              echo "Tagged v$VERSION"
            else
              echo "Tag v$VERSION already exists"
            fi
          fi